In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的参数，输入和输出节点。

In [2]:
batch_size = 8
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

#### 2. 定义前向传播过程，损失函数及反向传播算法。

In [17]:
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))) 
#train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)
train_step = tf.train.MomentumOptimizer(0.001, 0.9).minimize(cross_entropy)

####  3. 生成模拟数据集。

In [18]:
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]
#Y = [[int((x1>0.5 and x2<0.5) or (x1<0.5 and x2>0.5))] for (x1, x2) in X] # XOR problem

#### 4. 创建一个会话来运行TensorFlow程序。

In [19]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 输出目前（未经训练）的参数取值。
    print "w1:", sess.run(w1)
    print "w2:", sess.run(w2)
    print "\n"
    
    # 训练模型。
    STEPS = 5001
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
    
    # 输出训练后的参数取值。
    print "\n"
    print "w1:", sess.run(w1)
    print "w2:", sess.run(w2)

w1: [[-0.81131822  1.48459876  0.06532937]
 [-2.44270396  0.0992484   0.59122431]]
w2: [[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]


After 0 training step(s), cross entropy on all data is 0.0677127
After 1000 training step(s), cross entropy on all data is 0.0299578
After 2000 training step(s), cross entropy on all data is 0.0226611
After 3000 training step(s), cross entropy on all data is 0.0178286
After 4000 training step(s), cross entropy on all data is 0.0143322
After 5000 training step(s), cross entropy on all data is 0.0126648


w1: [[-1.14575207  1.92321956  0.10790702]
 [-2.79358888  0.57150626  0.63480961]]
w2: [[-1.77612603]
 [ 2.00361943]
 [ 0.25553519]]


In [15]:
tf.train.MomentumOptimizer?

In [9]:
X[:20]

array([[  4.17022005e-01,   7.20324493e-01],
       [  1.14374817e-04,   3.02332573e-01],
       [  1.46755891e-01,   9.23385948e-02],
       [  1.86260211e-01,   3.45560727e-01],
       [  3.96767474e-01,   5.38816734e-01],
       [  4.19194514e-01,   6.85219500e-01],
       [  2.04452250e-01,   8.78117436e-01],
       [  2.73875932e-02,   6.70467510e-01],
       [  4.17304802e-01,   5.58689828e-01],
       [  1.40386939e-01,   1.98101489e-01],
       [  8.00744569e-01,   9.68261576e-01],
       [  3.13424178e-01,   6.92322616e-01],
       [  8.76389152e-01,   8.94606664e-01],
       [  8.50442114e-02,   3.90547832e-02],
       [  1.69830420e-01,   8.78142503e-01],
       [  9.83468338e-02,   4.21107625e-01],
       [  9.57889530e-01,   5.33165285e-01],
       [  6.91877114e-01,   3.15515631e-01],
       [  6.86500928e-01,   8.34625672e-01],
       [  1.82882773e-02,   7.50144315e-01]])